sudo: required

language: go

go:
  - "1.10"

notifications:
  email: false

services:
  - docker

before_install:
- docker pull ebonetti/golang-petsc
  # Use the image from dockerhub only if it's updated.
- docker build --cache-from ebonetti/golang-petsc -t ebonetti/golang-petsc .
- |
  docker build -t test-env -<<<'
  FROM ebonetti/golang-petsc
  RUN go get github.com/ebonetti/absorbingmarkovchain/...;
  WORKDIR /go/src/github.com/ebonetti/absorbingmarkovchain
  '
- go get honnef.co/go/tools/cmd/megacheck/...;
- go get github.com/mattn/goveralls/...;

script:
- docker run test-env go test -v -race ./...
- megacheck ./...
- goveralls

after_script:
- docker rm -f test-env