sudo: required

install: true

notifications:
  email: false

services:
  - docker

before_install:
- docker pull ebonetti/golang-petsc
  # Use the image from dockerhub only if it's updated.
- docker build --cache-from ebonetti/golang-petsc -t ebonetti/golang-petsc .
- |
  docker build -t test-env -<<<'
  FROM ebonetti/golang-petsc
  ARG var_name
  ENV env_var_name=$var_name
  RUN  set -eux; \
  go get honnef.co/go/tools/cmd/megacheck/...; \
  go get github.com/mattn/goveralls/...; \
  go get github.com/ebonetti/absorbingmarkovchain/...;
  WORKDIR /go/src/github.com/ebonetti/absorbingmarkovchain
  '
- docker run -d -e COVERALLS_REPO_TOKEN --name test-env test-env sleep 600
- docker ps -a

script:
- docker exec test-env go test -v -race ./...
- docker exec test-env megacheck ./...
- docker exec test-env goveralls

after_script:
- docker rm -f test-env